server:
  port: 8088
spring:
  flyway:
    enabled: false

  # H2 配置
  datasource:
    driver-class-name: org.h2.Driver
    url:       jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;IGNORECASE=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;NON_KEYWORDS=user;DB_CLOSE_DELAY=-1

  h2:
    console:
      settings:
        trace: true
        web-allow-others: true
      enabled: true
      path: /h2-console
