spring:
    application:
        name: eureka-consumer-lite

eureka:
    client:
        service-url:
            # 是一个默认的注册中心地址。配置该选项后，可以在服务中心进行注册。
            defaultZone: http://${eureka.instance.hostname}:12211/eureka/
    instance:
        hostname: localhost

server:
    port: 12231
